#!/usr/bin/env node
/**
 * 紧急修复脚本：直接从 docs/ 目录的 .md 文件生成 sitemap.xml
 * 用于修复 sitemap.xml 为 0 字节的致命 SEO 问题
 * 
 * 使用：node scripts/emergency-sitemap.mjs
 */
import fs from 'fs'
import path from 'path'
import { fileURLToPath } from 'url'
import { execSync } from 'child_process'

const __filename = fileURLToPath(import.meta.url)
const __dirname = path.dirname(__filename)
const DOCS_DIR = path.resolve(__dirname, '../docs')
const SITEMAP_PATH = path.join(DOCS_DIR, 'public/sitemap.xml')
const DIST_SITEMAP_PATH = path.join(DOCS_DIR, '.vitepress/dist/sitemap.xml')

const HOSTNAME = 'https://friday-go.icu'

// 需要排除的路径前缀
const EXCLUDE_PREFIXES = [
  '/404',
  '/public/',
  '/.vitepress/',
]

// 需要排除的文件名
const EXCLUDE_FILES = [
  'index.md', // 根 index 会变成首页 URL，单独处理
]

function findAllMarkdownFiles(dir, baseDir = dir) {
  let results = []
  
  try {
    const entries = fs.readdirSync(dir, { withFileTypes: true })
    
    for (const entry of entries) {
      const fullPath = path.join(dir, entry.name)
      const relPath = path.relative(baseDir, fullPath)
      
      // 跳过隐藏目录、node_modules、public
      if (entry.name.startsWith('.') && entry.name !== '.vitepress') continue
      if (entry.name === 'node_modules') continue
      if (entry.name === 'public') continue
      
      if (entry.isDirectory()) {
        results = results.concat(findAllMarkdownFiles(fullPath, baseDir))
      } else if (entry.name.endsWith('.md')) {
        // 检查是否应该排除
        const urlPath = '/' + relPath.replace(/\.md$/, '').replace(/\\/g, '/')
        const shouldExclude = EXCLUDE_PREFIXES.some(p => urlPath.startsWith(p)) ||
                             EXCLUDE_FILES.some(f => relPath.endsWith(f))
        
        if (!shouldExclude) {
          results.push({
            filePath: fullPath,
            relPath: relPath,
            urlPath: urlPath
          })
        }
      }
    }
  } catch (e) {
    // 忽略权限错误等
  }
  
  return results
}

function getFileLastMod(filePath) {
  try {
    const stat = fs.statSync(filePath)
    return stat.mtime.toISOString()
  } catch {
    return new Date().toISOString()
  }
}

// 尝试从 git 获取最后修改时间（更准确）
function getGitLastMod(filePath) {
  try {
    const relativePath = path.relative(process.cwd(), filePath)
    const output = execSync(`git log -1 --format=%aI -- "${relativePath}"`, {
      encoding: 'utf-8',
      cwd: process.cwd(),
      timeout: 5000
    }).trim()
    if (output && output.length > 0) {
      return output
    }
  } catch {}
  return null
}

console.log('🔧 Emergency Sitemap Generator')
console.log('================================\n')

// 1. 找到所有 markdown 文件
const allFiles = findAllMarkdownFiles(DOCS_DIR)
console.log(`📂 Found ${allFiles.length} markdown files`)

// 2. 构建sitemap URL 列表
const urls = []

// 先添加首页
urls.push({
  loc: `${HOSTNAME}/`,
  lastmod: new Date().toISOString(),
  changefreq: 'daily',
  priority: '1.0'
})

// 专题索引页的高优先级路径
const indexPaths = [
  'dev', 'dev/backend', 'dev/backend/golang', 'dev/backend/php', 'dev/backend/python',
  'dev/system', 'dev/system/database',
  'security/engineering', 'security/offensive',
  'data/automation',
  'thinking/method', 'thinking/notes',
  'Tools',
  'courses',
  'Tools/online-tools'
]

for (const file of allFiles) {
  // 清理 URL 路径
  let urlPath = file.urlPath
  
  // 移除可能的 /index 后缀
  urlPath = urlPath.replace(/\/index$/, '') || '/'
  
  const fullUrl = `${HOSTNAME}${urlPath}`
  
  // 计算 priority
  const pathNorm = urlPath.replace(/^\//, '')
  let priority = '0.7'  // 默认文章优先级
  let changefreq = 'monthly'
  
  if (indexPaths.includes(pathNorm)) {
    priority = '0.9'
    changefreq = 'weekly'
  }
  
  // 获取修改时间
  let lastmod = getGitLastMod(file.filePath) || getFileLastMod(file.filePath)
  
  urls.push({ loc: fullUrl, lastmod, changefreq, priority })
}

// 3. 排序：优先级高的在前
urls.sort((a, b) => parseFloat(b.priority) - parseFloat(a.priority))

// 4. 生成 sitemap XML
const sitemapXml = `<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by emergency-sitemap.mjs on ${new Date().toISOString()} -->
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
${urls.map(u => `  <url>
    <loc>${u.loc}</loc>
    <lastmod>${u.lastmod}</lastmod>
    <changefreq>${u.changefreq}</changefreq>
    <priority>${u.priority}</priority>
  </url>`).join('\n')}
</urlset>`

// 5. 写入文件
fs.writeFileSync(SITEMAP_PATH, sitemapXml, 'utf-8')

// 也写入 dist 目录
if (fs.existsSync(path.dirname(DIST_SITEMAP_PATH))) {
  fs.writeFileSync(DIST_SITEMAP_PATH, sitemapXml, 'utf-8')
}

console.log(`✅ Sitemap generated with ${urls.length} URLs`)
console.log(`📄 Written to: ${SITEMAP_PATH}`)
console.log(`📦 Size: ${(Buffer.byteLength(sitemapXml) / 1024).toFixed(1)} KB`)

// 6. 统计信息
const byCategory = {}
for (const u of urls.slice(1)) { // 排除首页
  const parts = u.loc.replace(HOSTNAME, '').split('/').filter(Boolean)
  const category = parts[0] || 'other'
  byCategory[category] = (byCategory[category] || 0) + 1
}

console.log('\n📊 URLs by category:')
for (const [cat, count] of Object.entries(byCategory).sort((a, b) => b[1] - a[1])) {
  console.log(`   ${cat}: ${count}`)
}
